version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    executor: heroku/default

    working_directory: ~/Anzu

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
