version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Verifying Heroku Installation
          command: echo "Heroku installation successfull!"
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
